// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeExportDir(arg1) {
  return window['go']['main']['App']['ChangeExportDir'](arg1);
}

export function ExportReports(arg1, arg2) {
  return window['go']['main']['App']['ExportReports'](arg1, arg2);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
