// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeExportDir(arg1) {
  return window['go']['main']['App']['ChangeExportDir'](arg1);
}

export function ExportDailyReports(arg1, arg2) {
  return window['go']['main']['App']['ExportDailyReports'](arg1, arg2);
}

export function GetExportDir() {
  return window['go']['main']['App']['GetExportDir']();
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}
