// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeExportDir(arg1) {
  return window['go']['main']['App']['ChangeExportDir'](arg1);
}

export function ExportDailyReports(arg1, arg2) {
  return window['go']['main']['App']['ExportDailyReports'](arg1, arg2);
}

export function ExportPayrollWarnings(arg1) {
  return window['go']['main']['App']['ExportPayrollWarnings'](arg1);
}

export function ExportProgressEstimate(arg1) {
  return window['go']['main']['App']['ExportProgressEstimate'](arg1);
}

export function FetchPayrollEntries(arg1, arg2) {
  return window['go']['main']['App']['FetchPayrollEntries'](arg1, arg2);
}

export function GetExportDir() {
  return window['go']['main']['App']['GetExportDir']();
}

export function GetJobMaterialInfo(arg1, arg2) {
  return window['go']['main']['App']['GetJobMaterialInfo'](arg1, arg2);
}

export function GroupPayrollWarnings(arg1) {
  return window['go']['main']['App']['GroupPayrollWarnings'](arg1);
}

export function ProcessPayroll(arg1) {
  return window['go']['main']['App']['ProcessPayroll'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}
