// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dto} from '../models';
import {domain} from '../models';

export function ChangeExportDir(arg1:string):Promise<string>;

export function ExportDailyReports(arg1:string,arg2:string):Promise<void>;

export function ExportPayrollWarnings(arg1:Array<dto.Warning>):Promise<void>;

export function ExportProgressEstimate(arg1:Array<domain.JobMaterialInfo>):Promise<void>;

export function FetchPayrollEntries(arg1:string,arg2:string):Promise<dto.PayrollEntryResult>;

export function GetExportDir():Promise<string>;

export function GetJobMaterialInfo(arg1:string,arg2:string):Promise<Array<domain.JobMaterialInfo>>;

export function GroupPayrollWarnings(arg1:dto.PayrollEntryResult):Promise<Record<string, Array<dto.Warning>>>;

export function ProcessPayroll(arg1:dto.PayrollEntryResult):Promise<void>;

export function SelectFolder():Promise<string>;
